# Generated by Django 5.2 on 2025-05-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='card_image',
            field=models.ImageField(blank=True, default='default.png', max_length=300, upload_to=''),
        ),
    ]
