# Generated by Django 5.2 on 2025-05-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
